### PR TITLE
feature: add age and birthday fields

### PR DESCRIPTION
**Pull request by Rapougnac**
Maybe this can be useful for some people, and in general
I also updated the hitpoints model to the new health pool (since i forgot in my last pr)

### CODE REVIEW

**Comment by Rapougnac** [comment]
I don't know why the CI's failing

**Comment by TeKrop** [comment]
> I don't know why the CI's failing
Taking a look 👍

**Comment by TeKrop** [comment]
So there was many reasons : 
- When updating players fixtures, some test data needs to be updated. This is a wrong conception in the tests that I made a long time ago as a training, and I'm planning to completely rework them with my current knowledge
- Same thing for heroes fixtures, the corresponding JSON fixtures needs to be updated today
- There was some changes in new pydantic version, some error messages have changed and needed to be updated. This error came because I'm not using a versionned `poetry.lock` atm on the project to lock the dependencies, but will do.

I also took the liberty of reworking your changes : 
- I prefer to use regex here rather than a split followed by a [:1], this is completely a personal opinion
- I prefer to have a dedicated method (arbitrary put in parsers helper here)
- It gave me the occasion to add dedicated UT for it with the possible edge cases : Bastion's birthday is "Unknown", so I put a `null` value for his birthday

**Comment by Rapougnac** [comment]
Thanks for your changes!
I'm not really familiar with python projects and structures, my bad

**Comment by Rapougnac** [comment]
By the way (I totally forgot about this) but localized b/day and age are None when the language is an other value that english

**Comment by TeKrop** [comment]
> By the way (I totally forgot about this) but localized b/day and age are None when the language is an other value that english

Oh, good catch 🙈 Will make an update this week 👍

**Comment by TeKrop** [comment]
Fixed in https://github.com/TeKrop/overfast-api/pull/111 👍

**Pull request merged**
